### ISSUE TITLE
LexRating breaks superfish dropdown

### ISSUE THREAD

**Issue by estrata** [goldsky/LexRating#1]
I'm using Superfish to create a dropdown menu, and calling LexRating with this call ([[LexRating? &group=`roundabout` &userGroups=`Members`]]) breaks the dropdown.

Example:

http://www.ourston.com/orr/01087-windfields-farm.html

**Comment by goldsky** [comment]
you might want to add 

```
&loadjQuery=`0`
```

probably they have different versions.

**Comment by estrata** [comment]
That worked perfectly. Thanks for the quite reply!

LAURA ANDERTON

Freelance Graphic & Website Design 

for businesses, non-profits and individuals

 http://www.laura-anderton.com/ www.laura-anderton.com
